# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feira',
            name='referencia',
            field=models.CharField(blank=True, help_text='Ponto de refer\xeancia da localiza\xe7\xe3o da feira livre', max_length=24, null=True, verbose_name='Ponto de refer\xeancia'),
        ),
    ]
