# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feira', '0002_auto_20170318_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feira',
            name='id',
            field=models.AutoField(help_text='N\xfamero de identifica\xe7\xe3o do estabelecimento georreferenciado por SMDU/Deinfo', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
