test_data = {
    "com_id": {
        "id": 1,
        "distrito_nome": "VILA FORMOSA",
        "referencia": "ESQ. TV RUA PRETORIA",
        "regiao_5": "Leste",
        "longitude": "-46550164",
        "area_ponderacao": "3550308005040",
        "nome": "THE OLD VILA FORMOSA",
        "bairro": "VL FORMOSA",
        "subprefeitura_id": 26,
        "logradouro": "RUA MARAGOJIPE",
        "setor_censitario": "355030885000091",
        "numero": "Zero",
        "distrito_id": 187,
        "registro": "4041-0",
        "regiao_8": "Leste 1",
        "latitude": "-23558733",
        "subprefeitura_nome": "ARICANDUVA-FORMOSA-CARRAO"
    },

    "com_id_2": {
        "id": 2,
        "distrito_nome": "VILA PRUDENTE",
        "referencia": "RUA OLIVEIRA GOUVEIA",
        "regiao_5": "Leste",
        "longitude": "-46574716",
        "area_ponderacao": "3550308005042",
        "nome": "PRACA SANTA HELENA",
        "bairro": "VL ZELINA",
        "subprefeitura_id": 29,
        "logradouro": "RUA JOSE DOS REIS",
        "setor_censitario": "355030893000035",
        "numero": "909.000000",
        "distrito_id": 95,
        "registro": "4045-2",
        "regiao_8": "Leste 1",
        "latitude": "-23584852",
        "subprefeitura_nome": "VILA PRUDENTE"
    },

    "com_id_3": {
        "id": 3,
        "distrito_nome": "BRAS",
        "referencia": "TV RUA BRESSER",
        "regiao_5": "Leste",
        "longitude": "-46610332",
        "area_ponderacao": "3550308005005",
        "nome": "CONCORDIA",
        "bairro": "BRAS",
        "subprefeitura_id": 25,
        "logradouro": "RUA SAMPSON C MENDES JUNIOR",
        "setor_censitario": "355030810000027",
        "numero": "S/N",
        "distrito_id": 10,
        "registro": "4003-7",
        "regiao_8": "Leste 1",
        "latitude": "-23536131",
        "subprefeitura_nome": "MOOCA"
    },

    "sem_id": {
        "distrito_nome": "VILA FORMOSA",
        "referencia": "ESQ. TV RUA PRETORIA",
        "regiao_5": "Leste",
        "longitude": "-46550164",
        "area_ponderacao": "3550308005040",
        "nome": "THE OLD VILA FORMOSA",
        "bairro": "VL FORMOSA",
        "subprefeitura_id": 26,
        "logradouro": "RUA MARAGOJIPE",
        "setor_censitario": "355030885000091",
        "numero": "Zero",
        "distrito_id": 187,
        "registro": "4041-0",
        "regiao_8": "Leste 1",
        "latitude": "-23558733",
        "subprefeitura_nome": "ARICANDUVA-FORMOSA-CARRAO"
    },

    "faltando_campos": {
        "id": 1,
        "distrito_nome": "VILA FORMOSA",
        "referencia": "ESQ. TV RUA PRETORIA",
        "regiao_5": "Leste",
        # "longitude": "-46550164",
        "area_ponderacao": "3550308005040",
        "nome": "THE OLD VILA FORMOSA",
        "bairro": "VL FORMOSA",
        "subprefeitura_id": 26,
        "logradouro": "RUA MARAGOJIPE",
        "setor_censitario": "355030885000091",
        "numero": "Zero",
        "distrito_id": 187,
        "registro": "4041-0",
        "regiao_8": "Leste 1",
        "latitude": "-23558733",
        "subprefeitura_nome": "ARICANDUVA-FORMOSA-CARRAO"
    },

    "distrito_invalido": {
        # "distrito_nome": "VILA FORMOSA",
        "referencia": "ESQ. TV RUA PRETORIA",
        "regiao_5": "Leste",
        "longitude": "-46550164",
        "area_ponderacao": "3550308005040",
        "nome": "THE OLD VILA FORMOSA",
        "bairro": "VL FORMOSA",
        "subprefeitura_id": 26,
        "logradouro": "RUA MARAGOJIPE",
        "setor_censitario": "355030885000091",
        "numero": "Zero",
        "distrito_id": 187,
        "registro": "4041-0",
        "regiao_8": "Leste 1",
        "latitude": "-23558733",
        "subprefeitura_nome": "ARICANDUVA-FORMOSA-CARRAO"
    },
}

